import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs"; 
import { PhotoIcon, UserCircleIcon } from '@heroicons/react/24/solid'

function setJobSeeker()  {
  alert("You clicked me!");
}

function setEmployer()  {
  alert("You clicked me!");
}

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  const user = useUser();

  // const {data} = api.jobseeker.getAll.useQuery();

  //if (isLoading) return <div>Loading...</div>;

  //if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Super Staffing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>This page does not exist</h1>
      </main>
    </>
  );
}

export function ProfileCreation() {
  //const user = useUser();

  //const {data} = api.jobseeker.getAll.useQuery();

  return (
    <>
      <Head>
          <title>Super Staffing</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* header component */}
        <div className="flex border-b border-slate-400 p-4"> 
           Hello! Welcome to your profile creation!
        </div>
      </main>
    </>
  );
}

