import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs"; 

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
  const user = useUser();

  const {data} = api.posts.getAll.useQuery();

  //if (isLoading) return <div>Loading...</div>;

  //if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Super Staffing</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* header component */}
        <div className="flex border-b border-slate-400 p-4"> 
            {!user.isSignedIn && (
            <div className="signin">
              <SignInButton />
            </div>
            )}
            {!!user.isSignedIn && (
              <>
              <div className="signout">
                <SignOutButton />
              </div>
            </>
            )}
        </div>
        <div>
        {!!user.isSignedIn && (
              <>
              <div className="flex flex-col container">
                <h1 className="welcome">Welcome to Super Staffing!</h1>
                <h1 className="select-text">I am a...</h1>
                <p>Please select one</p>
                <h2>Job Seeker</h2>
                <h2>Employer</h2>
              </div>
            </>
            )}
        </div>
        <div className="w-full h-full md:max-w-2xl border-x border-slate-400">
          {/* <div className="flex flex-col">
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
            ))}
          </div> */}
        </div>
      </main>
    </>
  );
}
